/**
 * questions.js
 * Static question bank removed — all questions are now generated by the Gemini AI.
 * See js/gemini.js → fetchAiQuestions(category)
 */

/** Number of questions per test */
const QUESTIONS_PER_TEST = 10;
